// Static README.md template for the customer's mcp-server/ Worker.

export const README_TEMPLATE = `# {{brand_name}} MCP Server

Generated by Astrant Implementation. Deploy to your own Cloudflare account:

\`\`\`bash
cd mcp-server
npm install
npx wrangler login    # one-time, opens browser for OAuth
npx wrangler deploy
\`\`\`

After deploy, your MCP server is live at \`{{worker_name}}.<your-account>.workers.dev\`.

## Optional: branded URL via CNAME

Add a CNAME record in your DNS provider:

    mcp.{{domain}}  →  {{worker_name}}.<your-account>.workers.dev

Then update \`public/.well-known/mcp.json\` in your main site to point at the
branded URL instead of the workers.dev URL.

## What the Worker does

- \`GET /.well-known/mcp.json\` — returns your MCP discovery card (brand, domain, tools list).
- \`POST /mcp/call\` — dispatches one of 4 static tool responses (\`get_capabilities\`, \`get_pricing\`, \`get_case_studies\`, \`get_contact_tools\`).

All tool responses live in the \`TOOL_RESPONSES\` constant in \`index.ts\`. Edit
them freely in your repo — the Worker is yours.

## One-command future deploys

The \`npx @astrant/deploy-mcp\` wrapper (F2-pre-1, shipping shortly) automates
the \`wrangler login + deploy + mcp.json URL update\` sequence into a single
command. Until then, the manual three-line sequence above works.
`;
