// F2 v6.1 D15 — llms.txt generator.
//
// Engine version: f2:llms-txt:v1
// Output: customer's customized llms.txt content (text per llms.txt draft RFC).
// v1.0: deterministic fallback only (F2_LLM_ENABLED unset). LLM prompt + validators
// tuned in v1.1+ iteration with dogfood corpus.

import {
  generateWithTrustLadder,
  type F2LlmEnv,
  type PatchTimeGeneratorInput,
} from "./f2-llm-helpers";

const ENGINE_VERSION = "f2:llms-txt:v1";

export async function generateLlmsTxt(
  env: F2LlmEnv,
  input: PatchTimeGeneratorInput,
): Promise<string> {
  const result = await generateWithTrustLadder<string>(env, {
    engineVersion: ENGINE_VERSION,
    cacheKeyInput: input as unknown as Record<string, unknown>,
    callModel: async () => null,           // v1.0: not wired; deterministic only
    validators: [],
    retryWithFeedback: async () => null,
    fallback: () => buildDeterministicLlmsTxt(input),
    serialize: (s) => s,
    deserialize: (s) => s,
  });
  return result.value;
}

// Deterministic, audit-disciplined llms.txt. Per llms.txt draft RFC:
//   - H1 with the product name
//   - Blockquote summary
//   - One or more sections of curated links
function buildDeterministicLlmsTxt(input: PatchTimeGeneratorInput): string {
  const competitors = input.competitors.length
    ? `\n## Alternatives\nCustomers comparing ${input.brand_name} sometimes also evaluate ${input.competitors.join(", ")}.\n`
    : "";
  return `# ${input.brand_name}

> ${input.brand_name} provides ${input.category} services at ${input.domain}.

## Documentation
- [Homepage](https://${stripScheme(input.domain)}/)

## API
- Customer-maintained. Edit this section to link your OpenAPI spec, API docs,
  and authentication overview.

## Capabilities
- Customer-maintained. Edit this section to describe what ${input.brand_name}
  does for agents querying on behalf of users.
${competitors}
## Maintenance
- Generated by Astrant Implementation. Edit any section above; the file is
  yours. Re-run scoring at https://astrant.io/audit to validate changes.
`;
}

function stripScheme(domain: string): string {
  return domain.replace(/^https?:\/\//, "").replace(/\/$/, "");
}
